---
# CVMFS client installation and configuration
# Based on official galaxyproject.cvmfs role

- name: Install CVMFS prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present
    update_cache: yes

- name: Install CernVM apt key
  ansible.builtin.apt_key:
    url: https://cvmrepo.web.cern.ch/cvmrepo/apt/cernvm.gpg

- name: Configure CernVM apt repository for Ubuntu noble (24.04)
  ansible.builtin.apt_repository:
    filename: cernvm.list
    mode: 422
    repo: deb [allow-insecure=true] https://cvmrepo.web.cern.ch/cvmrepo/apt/ {{ ansible_distribution_release }}-prod main
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release in ('bionic', 'xenial', 'precise', 'focal', 'jammy', 'noble')

- name: Configure CernVM apt repository fallback for unsupported Ubuntu versions
  ansible.builtin.apt_repository:
    filename: cernvm.list
    mode: 422
    repo: deb [allow-insecure=true] https://cvmrepo.web.cern.ch/cvmrepo/apt/ xenial-prod main
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release not in ('bionic', 'xenial', 'precise', 'focal', 'jammy', 'noble')

- name: Install CVMFS client
  ansible.builtin.apt:
    name: cvmfs
    state: present
    update_cache: yes

- name: Create CVMFS keys directory
  ansible.builtin.file:
    path: /etc/cvmfs/keys/galaxyproject.org
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Install Galaxy CVMFS config repository key
  ansible.builtin.copy:
    content: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuJZTWTY3/dBfspFKifv8
      TWuuT2Zzoo1cAskKpKu5gsUAyDFbZfYBEy91qbLPC3TuUm2zdPNsjCQbbq1Liufk
      uNPZJ8Ubn5PR6kndwrdD13NVHZpXVml1+ooTSF5CL3x/KUkYiyRz94sAr9trVoSx
      THW2buV7ADUYivX7ofCvBu5T6YngbPZNIxDB4mh7cEal/UDtxV683A/5RL4wIYvt
      S5SVemmu6Yb8GkGwLGmMVLYXutuaHdMFyKzWm+qFlG5JRz4okUWERvtJ2QAJPOzL
      mAG1ceyBFowj/r3iJTa+Jcif2uAmZxg+cHkZG5KzATykF82UH1ojUzREMMDcPJi2
      dQIDAQAB
      -----END PUBLIC KEY-----
    dest: /etc/cvmfs/keys/galaxyproject.org/cvmfs-config.galaxyproject.org.pub
    owner: root
    group: root
    mode: '0444'

- name: Install Galaxy CVMFS general key
  ansible.builtin.copy:
    content: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuJZTWTY3/dBfspFKifv8
      TWuuT2Zzoo1cAskKpKu5gsUAyDFbZfYBEy91qbLPC3TuUm2zdPNsjCQbbq1Liufk
      uNPZJ8Ubn5PR6kndwrdD13NVHZpXVml1+ooTSF5CL3x/KUkYiyRz94sAr9trVoSx
      THW2buV7ADUYivX7ofCvBu5T6YngbPZNIxDB4mh7cEal/UDtxV683A/5RL4wIYvt
      S5SVemmu6Yb8GkGwLGmMVLYXutuaHdMFyKzWm+qFlG5JRz4okUWERvtJ2QAJPOzL
      mAG1ceyBFowj/r3iJTa+Jcif2uAmZxg+cHkZG5KzATykF82UH1ojUzREMMDcPJi2
      dQIDAQAB
      -----END PUBLIC KEY-----
    dest: /etc/cvmfs/keys/galaxyproject.org/galaxyproject.org.pub
    owner: root
    group: root
    mode: '0444'

- name: Install Galaxy CVMFS data repository key
  ansible.builtin.copy:
    content: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5LHQuKWzcX5iBbCGsXGt
      6CRi9+a9cKZG4UlX/lJukEJ+3dSxVDWJs88PSdLk+E25494oU56hB8YeVq+W8AQE
      3LWx2K2ruRjEAI2o8sRgs/IbafjZ7cBuERzqj3Tn5qUIBFoKUMWMSIiWTQe2Sfnj
      GzfDoswr5TTk7aH/FIXUjLnLGGCOzPtUC244IhHARzu86bWYxQJUw0/kZl5wVGcH
      maSgr39h1xPst0Vx1keJ95AH0wqxPbCcyBGtF1L6HQlLidmoIDqcCQpLsGJJEoOs
      NVNhhcb66OJHah5ppI1N3cZehdaKyr1XcF9eedwLFTvuiwTn6qMmttT/tHX7rcxT
      owIDAQAB
      -----END PUBLIC KEY-----
    dest: /etc/cvmfs/keys/galaxyproject.org/data.galaxyproject.org.pub
    owner: root
    group: root
    mode: '0444'

- name: Install Galaxy CVMFS main repository key
  ansible.builtin.copy:
    content: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6S6Tugcv4kk4C06f574l
      YCXQdK6lv2m7mqCh60G0zL1+rAkkEBDWna0yMQLBbj+yDsHjcOe0yISzbTfzG6wk
      KnHZUQ/JOeK7lUAbDMxHqnjkEPAbAl4vXl2Y04MW2lzJtXcDKakmLirvV/dfUYqE
      gGGx0dc/Z+XmUTf1DvZFJknrBUUxO5+F6m7k/NGrlpAca+e9B0kwCclaE4NyaNWK
      Jv5rPWCYz5/sDNW4cNvBdBjwGf46etbczmJoTAbl0oM6LLGdebwkJStd0R1wkj+A
      torRYcoFZICTZqY9e/KsadHUeZnH3RvfMypH5oS1POzsFszoSxBhZIBkZbG3/f9Y
      OQIDAQAB
      -----END PUBLIC KEY-----
    dest: /etc/cvmfs/keys/galaxyproject.org/main.galaxyproject.org.pub
    owner: root
    group: root
    mode: '0444'

- name: Configure CVMFS domain
  ansible.builtin.copy:
    content: |
      ## This file is maintained by Ansible - CHANGES WILL BE OVERWRITTEN
      CVMFS_SERVER_URL="http://cvmfs1-psu0.galaxyproject.org/cvmfs/@fqrn@;http://cvmfs1-iu0.galaxyproject.org/cvmfs/@fqrn@;http://cvmfs1-tacc0.galaxyproject.org/cvmfs/@fqrn@;http://cvmfs1-mel0.gvl.org.au/cvmfs/@fqrn@;http://cvmfs1-ufr0.galaxyproject.eu/cvmfs/@fqrn@"
      CVMFS_KEYS_DIR=/etc/cvmfs/keys/galaxyproject.org
      CVMFS_USE_GEOAPI=no
    dest: /etc/cvmfs/domain.d/galaxyproject.org.conf
    owner: root
    group: root
    mode: '0444'

- name: Configure CVMFS global client settings
  ansible.builtin.copy:
    content: |
      CVMFS_REPOSITORIES="test.galaxyproject.org,main.galaxyproject.org,data.galaxyproject.org,refgenomes-databio.galaxyproject.org,sandbox.galaxyproject.org,singularity.galaxyproject.org,usegalaxy.galaxyproject.org"
      CVMFS_HTTP_PROXY=DIRECT
      CVMFS_QUOTA_LIMIT=4000
      CVMFS_CACHE_BASE=/var/lib/cvmfs
    dest: /etc/cvmfs/default.local
    owner: root
    group: root
    mode: '0644'

- name: Check CernVM-FS for setup
  ansible.builtin.command: cvmfs_config chksetup
  changed_when: false
  ignore_errors: true
  register: cvmfs_config_chksetup_out

- name: Ensure AutoFS is enabled + running
  ansible.builtin.service:
    name: autofs
    enabled: true
    state: started

- name: Perform AutoFS and FUSE configuration for CernVM-FS
  ansible.builtin.command: cvmfs_config setup
  when: not ansible_check_mode and "CernVM-FS map is not referenced" in cvmfs_config_chksetup_out.stdout
