---
- name: Download Helm installation script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: "0755"
  become: true

- name: Install Helm
  ansible.builtin.shell:
    cmd: /tmp/get_helm.sh --version {{ helm_version }}
    creates: /usr/local/bin/helm
  become: true
  environment:
    DESIRED_VERSION: "{{ helm_version }}"

- name: Remove Helm installation script
  ansible.builtin.file:
    path: /tmp/get_helm.sh
    state: absent
  become: true

- name: Verify Helm installation
  ansible.builtin.command: /usr/local/bin/helm version --short
  register: helm_version_output
  changed_when: false
  become: true

- name: Display Helm version
  ansible.builtin.debug:
    msg: "Installed Helm version: {{ helm_version_output.stdout }}"

- name: Create Helm config directory for ubuntu user
  ansible.builtin.file:
    path: /home/ubuntu/.config/helm
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  become: true

- name: Create Helm cache directory for ubuntu user
  ansible.builtin.file:
    path: /home/ubuntu/.cache/helm
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  become: true

- name: Add stable Helm repository (pre-cache for faster deployment)
  ansible.builtin.shell: |
    /usr/local/bin/helm repo add stable https://charts.helm.sh/stable
  become: true
  become_user: ubuntu
  environment:
    HOME: /home/ubuntu
  failed_when: false
  changed_when: false

- name: Add CloudVE Helm repository (pre-cache for faster deployment)
  ansible.builtin.shell: |
    /usr/local/bin/helm repo add cloudve https://raw.githubusercontent.com/CloudVE/helm-charts/master/
  become: true
  become_user: ubuntu
  environment:
    HOME: /home/ubuntu
  failed_when: false
  changed_when: false

- name: Update Helm repositories to cache index files
  ansible.builtin.shell: |
    /usr/local/bin/helm repo update
  become: true
  become_user: ubuntu
  environment:
    HOME: /home/ubuntu
  failed_when: false
  changed_when: false

- name: Verify Helm repositories are cached
  ansible.builtin.shell: |
    /usr/local/bin/helm repo list
  become: true
  become_user: ubuntu
  environment:
    HOME: /home/ubuntu
  register: helm_repos_check
  failed_when: false
  changed_when: false

- name: Display cached Helm repositories
  ansible.builtin.debug:
    msg: "Cached Helm repositories: {{ helm_repos_check.stdout_lines }}"
  when: helm_repos_check.rc == 0
