---
# Configure essential kernel parameters and system settings required for Kubernetes/RKE2 to function properly.
# These settings enable container networking, disable swap, and configure bridge netfilter for pod communication.

- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/99-kubernetes.conf
  become: true

- name: Add kernel modules to load at boot
  ansible.builtin.copy:
    content: |
      br_netfilter
      overlay
    dest: /etc/modules-load.d/k8s.conf
    mode: "0644"
  become: true

- name: Load kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - br_netfilter
    - overlay
  become: true

- name: Set bridge-nf-call-iptables
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/99-kubernetes.conf
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
  become: true

- name: Disable swap permanently in /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^(.+?\sswap\s+.*)$'
    replace: '# \1'
  become: true

- name: Disable swap immediately
  ansible.builtin.command: swapoff -a
  become: true
  changed_when: false

- name: Create /mnt/block_storage directory
  ansible.builtin.file:
    path: /mnt/block_storage
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  become: true

- name: Add KUBECONFIG to ubuntu user's .bashrc
  ansible.builtin.lineinfile:
    path: /home/ubuntu/.bashrc
    line: 'export KUBECONFIG=/etc/rancher/rke2/rke2.yaml'
    create: true
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Add RKE2 bin directory to ubuntu user's PATH
  ansible.builtin.lineinfile:
    path: /home/ubuntu/.bashrc
    line: 'export PATH=/var/lib/rancher/rke2/bin:$PATH'
    create: true
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Download LS_COLORS configuration
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/trapd00r/LS_COLORS/master/LS_COLORS
    dest: /home/ubuntu/.LS_COLORS
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Enable LS_COLORS in ubuntu user's .bashrc
  ansible.builtin.lineinfile:
    path: /home/ubuntu/.bashrc
    line: 'eval "$(dircolors -b ~/.LS_COLORS)"'
    create: true
    owner: ubuntu
    group: ubuntu
    mode: '0644'
