---
# Unified Galaxy/Pulsar Kubernetes deployment playbook
# Optimized for pre-prepared images with RKE2 prerequisites and Helm
#
# Host Group: vm
#
# Usage Examples:
#   # Deploy Galaxy (default):
#   ansible-playbook -i inventory playbook.yml
#
#   # Deploy Pulsar instead of Galaxy:
#   ansible-playbook -i inventory playbook.yml -e "application=pulsar"
#
#   # Deploy on bare Ubuntu (full setup):
#   ansible-playbook -i inventory playbook.yml -e "setup_system=true"

- name: Deploy Galaxy/Pulsar on Kubernetes
  hosts: vm
  gather_facts: true
  become: true
  roles:
    - role: galaxy_k8s_deployment
      vars:
        setup_system: false    # Skip - already installed in image (includes Helm)
                               # Set to true via -e for bare Ubuntu VMs
        setup_rke2: true       # Configure and start RKE2
        setup_nfs: true
        setup_storage: true
        setup_ingress: true
        deploy_galaxy: "{{ application | default('galaxy') == 'galaxy' }}"
        deploy_pulsar: "{{ application | default('galaxy') == 'pulsar' }}"
        galaxy_values_file: "values/{{ chart_values_file | default('values.yml') }}"
        galaxy_user: "{{ galaxy_admin_users | default('admin@galaxyproject.org') }}"
