---
# External Ansible roles and collections required for galaxy-k8s-boot

collections:
  - name: community.general
    version: ">=11.3.0"
  - name: ansible.posix
    version: ">=2.1.0"
  - name: kubernetes.core
    version: ">=6.1.0"

roles:
  - name: galaxyproject.cvmfs
    version: ">=0.3.2"
  - name: lablabs.rke2
    version: ">=1.48.0"
