---
# Fast runtime playbook for pre-prepared images
# This playbook assumes components are already installed via image_preparation.yml

- name: Quick setup verification for pre-prepared image
  hosts: nodes
  gather_facts: false
  tasks:
    - name: Verify image preparation marker exists
      stat:
        path: /etc/galaxy-k8s-boot-image-info
      register: image_marker

    - name: Fail if image not prepared
      fail:
        msg: |
          This instance doesn't appear to be created from a prepared image.
          Please run image_preparation.yml first or use a prepared AMI/image.
      when: not image_marker.stat.exists

    - name: Display image info
      command: cat /etc/galaxy-k8s-boot-image-info
      register: image_info
      changed_when: false

    - name: Show image preparation details
      debug:
        msg: "{{ image_info.stdout }}"

- name: Configure runtime-specific settings
  hosts: nodes
  tasks:
    - name: Regenerate SSH host keys
      shell: |
        ssh-keygen -A
        systemctl restart ssh
      become: true
      when: ansible_os_family == "Debian"

    - name: Regenerate SSH host keys (RHEL/CentOS)
      shell: |
        ssh-keygen -A
        systemctl restart sshd
      become: true
      when: ansible_os_family == "RedHat"

    - name: Start required services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: true
        daemon_reload: true
      loop:
        - containerd
        - autofs
      become: true
      ignore_errors: true

    - name: Initialize machine-id
      shell: systemd-machine-id-setup
      become: true
      ignore_errors: true

- name: Setup Kubernetes cluster (streamlined)
  import_playbook: k3s/site.yml

- name: Install Helm repositories (runtime configuration)
  hosts: controllers[0]
  environment:
    KUBECONFIG: "{{ '/root' if ansible_user == 'root' else '/home/' + ansible_user }}/.kube/config"
  tasks:
    - name: Add stable Helm repository
      kubernetes.core.helm_repository:
        name: stable
        repo_url: https://charts.helm.sh/stable
        state: present

    - name: Add CloudVE Helm repository
      kubernetes.core.helm_repository:
        name: cloudve
        repo_url: https://raw.githubusercontent.com/CloudVE/helm-charts/master/
        state: present

- name: Configure storage
  import_playbook: storage.yml

- name: Configure Ingress
  import_playbook: ingress.yml

- name: Install Galaxy
  import_playbook: galaxy_app.yml
  vars:
    values_file: "values/{{ chart_values_file | default('accp.yml') }}"
    gxy_admin_users: "{{ galaxy_admin_users | default('') }}"
    gxy_api_key: "{{ galaxy_api_key }}"
  when: application == "galaxy"

- name: Install Pulsar
  import_playbook: pulsar.yml
  vars:
    pulsar_api_key: "{{ pulsar_api_key }}"
  when: application == "pulsar"
