---
- name: Basic setup of the node
  hosts: nodes
  tasks:
    - name: Install system packages
      ansible.builtin.apt:
        name: "{{ install_packages }}"
        state: present
        update_cache: true
      become: true
      vars:
        install_packages:
          - python3
          - python3-pip
          - python3-openshift  # Required by the Ansible Kubernetes module
          - nfs-common
