---
# Pulsar Application Setup Tasks
- name: Create the Pulsar namespace
  kubernetes.core.k8s:
    kind: Namespace
    name: pulsar
    state: present
    kubeconfig: "{{ kubeconfig_path }}"

- name: Helm install pulsar-deps
  kubernetes.core.helm:
    name: pulsar-deps
    namespace: pulsar
    chart_ref: "cloudve/galaxy-deps"
    chart_version: "{{ pulsar_deps_version }}"
    kubeconfig: "{{ kubeconfig_path }}"
    values:
      cvmfs:
        deploy: true
      postgresql:
        deploy: false
      rabbitmq:
        deploy: false

- name: Helm install Pulsar
  kubernetes.core.helm:
    name: pulsar
    namespace: pulsar
    chart_ref: "{{ pulsar_chart }}"
    chart_version: "{{ pulsar_chart_version }}"
    kubeconfig: "{{ kubeconfig_path }}"
    values:
      api_key: "{{ pulsar_api_key }}"
      resources:
        requests:
          cpu: 0.5
          memory: 1Gi
      refdata:
        enabled: true
      persistence:
        storageClass: "blockstorage"
        accessModes:
          - ReadWriteOnce
      securityContext:
        # apptainer needs privileged mode to run within the pulsar container.
        # docker runs a privileged container as a sidecar.
        privileged: true
