---
# Kubernetes Storage Setup Tasks
- name: Render the hostpath storage class template
  kubernetes.core.k8s:
    template:
      path: templates/hostpath_storage_class.yaml.j2
    state: present
    kubeconfig: "{{ kubeconfig_path }}"

- name: Render the elastic block storage class
  kubernetes.core.k8s:
    template:
      path: block_storage_storageclass.yml.j2
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
