---
# System Setup Tasks
- name: Install system packages
  ansible.builtin.apt:
    name: "{{ system_packages }}"
    state: present
    update_cache: true
  become: true

- name: Install Helm
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: "set -o pipefail && curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash -s"
    creates: /usr/local/bin/helm
  become: true

- name: Remove existing stable Helm repo
  kubernetes.core.helm_repository:
    name: stable
    state: absent

- name: Install Helm repositories
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    state: present
    repo_url: "{{ item.url }}"
  loop: "{{ helm_repositories }}"
