---
# Container prefetch role - pre-pulls container images for faster runtime deployment

- name: Load container images configuration
  include_vars: "{{ container_images_config_file }}"
  when: container_prefetch_enabled | bool

- name: Ensure containerd is running for image pulling
  systemd:
    name: containerd
    state: started
    enabled: true
    daemon_reload: true
  become: true
  when: container_prefetch_enabled | bool

- name: Pre-fetch container images using containerd directly
  shell: ctr -n {{ container_prefetch_namespace }} images pull {{ item }}
  register: pull_result
  failed_when: false
  changed_when: pull_result.rc == 0 and 'already exists' not in pull_result.stderr
  loop: "{{ container_images | default([]) }}"
  loop_control:
    label: "{{ item }}"
  when: container_prefetch_enabled | bool
  become: true

- name: Verify container images are available
  block:
    - name: List pulled images
      shell: ctr -n {{ container_prefetch_namespace }} images list
      register: pulled_images_list
      changed_when: false

    - name: Display pulled images summary
      debug:
        msg: |
          Container images pre-fetch complete!
          Total images available: {{ pulled_images_list.stdout_lines | length - 1 }}

          Use 'ctr -n {{ container_prefetch_namespace }} images list' to see all cached images.

  when: container_prefetch_enabled | bool
  become: true
