---
# Default variables for image preparation role
rke2_version: v1.34.1+rke2r1  # https://github.com/rancher/rke2/tags
helm_version: v3.19.0  # https://github.com/helm/helm/tags

# System packages to install (Ubuntu focused)
base_packages:
  - python3
  - python3-pip
  - python3-openshift
  - nfs-common
  - curl
  - wget
  - unzip
  - tar
  - git
  - jq
  - vim
  - gnupg
  - ca-certificates
  - ansible

# Enable/disable components
install_base_packages: true
install_cvmfs: true
install_rke2_prerequisites: true
install_helm: true
install_docker: true
prefetch_container_images: true

# Container prefetch configuration
container_prefetch_image_pull_retries: 3
container_prefetch_image_pull_delay: 5
