postInstallJob:
  imports:
    workflows:
      - "https://raw.githubusercontent.com/galaxyproject/iwc/refs/heads/main/workflows/transcriptomics/rnaseq-pe/rnaseq-pe.ga"
    datasets:
      - url: "https://zenodo.org/records/13987631/files/Saccharomyces_cerevisiae.R64-1-1.113.gtf"
        fileType: "gtf"
        history: "Imported Datasets"
      - url: "https://zenodo.org/records/13987631/files/SRR5085167_forward.fastqsanger.gz"
        history: "Imported Datasets"
      - url: "https://zenodo.org/records/13987631/files/SRR5085167_reverse.fastqsanger.gz"
        history: "Imported Datasets"
